name: Upload to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@v3
        with:
          source_dir: './'
          container_name: 'tokyo-olympic-data'
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
